Repository netascode/ansible-dc-vxlan, pull requests merged in 2024-11, with the labels that each got.

#216 Refactor rule 301 and 401 to simplify code
  roles/validate/files/rules/required_rules/301_topology_switch_serial.py
  roles/validate/files/rules/required_rules/401_overlay_services_cross_reference.py
Labels: r0.3.0

#214 Update ndfc_policy.j2
  roles/dtc/common/templates/ndfc_policy.j2
Labels: r0.3.0

#211 Change attach_group for vrfs and networks
  plugins/action/common/prepare_plugins/prep_104_fabric_overlay_services.py
  roles/dtc/common/templates/ndfc_attach_networks.j2
  roles/dtc/common/templates/ndfc_attach_vrfs.j2
  tests/integration/host_vars/examples/fabric_full_large_example/networks.yaml
  tests/integration/host_vars/examples/fabric_full_large_example/vrfs.yaml
  tests/integration/host_vars/examples/fabric_full_small_isis_ingress_example/networks.yaml
  tests/integration/host_vars/examples/fabric_full_small_isis_ingress_example/vrfs.yaml
  tests/integration/host_vars/examples/fabric_full_small_isis_multicast_asm_example/networks.yaml
  tests/integration/host_vars/examples/fabric_full_small_isis_multicast_asm_example/vrfs.yaml
  tests/integration/host_vars/examples/fabric_full_small_isis_multicast_bidir_example/networks.yaml
  tests/integration/host_vars/examples/fabric_full_small_isis_multicast_bidir_example/vrfs.yaml
  tests/integration/host_vars/examples/fabric_full_small_ospf_ingress_example/networks.yaml
  tests/integration/host_vars/examples/fabric_full_small_ospf_ingress_example/vrfs.yaml
  tests/integration/host_vars/examples/fabric_full_small_ospf_multicast_asm_example/networks.yaml
  tests/integration/host_vars/examples/fabric_full_small_ospf_multicast_asm_example/vrfs.yaml
  tests/integration/host_vars/examples/fabric_full_small_ospf_multicast_bidir_example/networks.yaml
  tests/integration/host_vars/examples/fabric_full_small_ospf_multicast_bidir_example/vrfs.yaml
  tests/integration/host_vars/examples/fabric_full_small_sha_example/networks.yaml
  tests/integration/host_vars/examples/fabric_full_small_sha_example/vrfs.yaml
Labels: r0.3.0

#215 Handle stale serial number issue for hostname policy
  plugins/action/helper_functions.py
Labels: r0.3.0

#164 Add Fabric STP
  roles/dtc/common/templates/ndfc_create_fabric.j2
  roles/dtc/common/templates/ndfc_interface_trunk.j2
  roles/dtc/common/templates/ndfc_interface_trunk_po.j2
  roles/dtc/common/templates/ndfc_utils.j2
  roles/dtc/create/tasks/sub_main.yml
  roles/validate/files/defaults.yml
  roles/validate/files/rules/required_rules/201_global_spanning_tree.py
Labels: enhancement, r0.3.0

#204 Enable POAP Bootstrap Workflow
  plugins/action/dtc/get_poap_data.py
  roles/dtc/common/tasks/main.yml
  roles/dtc/common/tasks/ndfc_inventory.yml
  roles/dtc/common/templates/ndfc_create_fabric.j2
  roles/dtc/common/templates/ndfc_fabric/dc_vxlan_fabric/bootstrap/dc_vxlan_fabric_bootstrap.j2
  roles/dtc/common/templates/ndfc_fabric/dc_vxlan_fabric/dc_vxlan_fabric_base.j2
  roles/dtc/common/templates/ndfc_inventory.j2
  roles/dtc/common/templates/ndfc_policy.j2
  roles/dtc/create/tasks/devices_poap.yml
  roles/dtc/create/tasks/devices_preprovision.yml
  roles/dtc/create/tasks/sub_main.yml
  roles/validate/tasks/sub_main.yml
  tests/sanity/ignore-2.14.txt
  tests/sanity/ignore-2.15.txt
  tests/sanity/ignore-2.16.txt
Labels: r0.3.0

#225 Fix tags
  plugins/action/common/check_roles.py
  roles/common_global/vars/main.yml
  roles/dtc/common/meta/main.yml
  roles/dtc/common/tasks/main.yml
  roles/dtc/connectivity_check/tasks/main.yml
  roles/dtc/connectivity_check/tasks/verify_ndfc_authorization.yml
  roles/dtc/connectivity_check/tasks/verify_ndfc_connectivity.yml
  roles/dtc/create/meta/main.yml
  roles/dtc/deploy/meta/main.yml
  roles/dtc/deploy/tasks/main.yml
  roles/dtc/remove/meta/main.yml
  roles/validate/tasks/main.yml
Labels: r0.3.0

#224 Update nac_dc_validate to check if iac-validate is installed
  plugins/action/common/nac_dc_validate.py
Labels: enhancement

#229 Update vrfs_networks.yml
  roles/dtc/create/tasks/vrfs_networks.yml
Labels: r0.3.0

#181 Initial VRF-Lite for NDFC
  plugins/action/common/prepare_plugins/prep_107_policy.py
  plugins/action/common/prepare_plugins/prep_107_vrf_lites.py
  plugins/action/common/prepare_service_model.py
  plugins/plugin_utils/helper_functions.py
  requirements.txt
  roles/dtc/common/templates/ndfc_vrf_lite.j2
  roles/dtc/common/templates/ndfc_vrf_lite_ebgp.j2
  roles/dtc/common/templates/ndfc_vrf_lite_ospf.j2
  roles/render/README.md
  roles/render/defaults/main.yml
  roles/render/files/.gitkeep
  roles/render/handlers/main.yml
  roles/render/meta/main.yml
  roles/render/tasks/main.yml
  roles/render/templates/.keep
  roles/render/tests/inventory
  roles/render/tests/test.yml
  roles/render/vars/main.yml
  roles/validate/files/defaults.yml
  roles/validate/files/rules/required_rules/502_policy_vrf_lite_cross_reference.py
  roles/validate/tasks/sub_main.yml
  tests/sanity/ignore-2.14.txt
  tests/sanity/ignore-2.15.txt
  tests/sanity/ignore-2.16.txt
Labels: r1.0, ready for review

#233 updated prepare plugins to create new ip address field instead of replacing hostname
  plugins/action/common/prepare_plugins/prep_103_topology_switches.py
  plugins/action/common/prepare_plugins/prep_104_fabric_overlay_services.py
  plugins/plugin_utils/helper_functions.py
  roles/dtc/common/templates/ndfc_attach_networks.j2
  roles/dtc/common/templates/ndfc_attach_vrfs.j2
  roles/dtc/common/templates/ndfc_policy.j2
Labels: ready for review
