Repository netascode/ansible-dc-vxlan, pull requests merged in 2025-07, with the labels that each got.

#431 Fix poap invalid fabric
  plugins/action/dtc/get_poap_data.py
Labels: ready for review, 0.4.3

#406 Fix for Ingress replication is not allowed for border_gateway_spine
  roles/validate/files/rules/vxlan/207_global_replication.py
Labels: bug, 0.4.3

#433 Fixes for 0.4.3
  plugins/action/dtc/unmanaged_child_fabric_networks.py
  plugins/action/dtc/unmanaged_child_fabric_vrfs.py
  roles/dtc/common/tasks/main.yml
  roles/dtc/common/tasks/msd/ndfc_bgw_anycast_vip.yml
  roles/dtc/common/tasks/sub_main_msd.yml
  roles/dtc/common/templates/ndfc_bgw_anycast_vip.j2
  roles/dtc/create/tasks/common/vpc_peering.yml
  roles/dtc/create/tasks/main.yml
  roles/dtc/create/tasks/msd/vrfs_networks.yml
  roles/dtc/create/tasks/sub_main_msd.yml
  tests/integration/roles/test_update_model_data/tasks/main.yml
Labels: 0.4.3

#434 Release Notes for 0.4.3
  CHANGELOG.rst
  README.md
  docs/maintainers.md
  galaxy.yml
Labels: 0.4.3

#448 Update 204_global_bootstrap.py
  roles/validate/files/rules/vxlan/204_global_bootstrap.py
Labels: ready for review, 0.5.0

#452 Fix remove device issue for isn external
  roles/dtc/common/tasks/sub_main_external.yml
  roles/dtc/common/tasks/sub_main_isn.yml
Labels: ready for review

#477 Update isn_fabric_inventory.j2
  roles/dtc/common/templates/ndfc_inventory/isn_fabric/isn_fabric_inventory.j2
Labels: ready for review

#469 Fix msd without child
  roles/dtc/common/templates/ndfc_bgw_anycast_vip.j2
  roles/dtc/deploy/tasks/sub_main_msd.yml
  roles/dtc/remove/tasks/msd/networks.yml
  roles/dtc/remove/tasks/msd/vrfs.yml
Labels: ready for review, 0.5.0

#460 Initial eBGP Fabric Support
  plugins/action/common/nac_dc_validate.py
  roles/dtc/common/tasks/main.yml
  roles/dtc/common/tasks/sub_main_ebgp_vxlan.yml
  roles/dtc/common/templates/ndfc_fabric.j2
  roles/dtc/common/templates/ndfc_fabric/ebgp_vxlan_fabric/.gitkeep
  roles/dtc/common/templates/ndfc_fabric/ebgp_vxlan_fabric/advanced/.gitkeep
  roles/dtc/common/templates/ndfc_fabric/ebgp_vxlan_fabric/advanced/ebgp_vxlan_fabric_advanced.j2
  roles/dtc/common/templates/ndfc_fabric/ebgp_vxlan_fabric/bootstrap/.gitkeep
  roles/dtc/common/templates/ndfc_fabric/ebgp_vxlan_fabric/bootstrap/ebgp_vxlan_fabric_bootstrap.j2
  roles/dtc/common/templates/ndfc_fabric/ebgp_vxlan_fabric/ebgp_vxlan_fabric_base.j2
  roles/dtc/common/templates/ndfc_fabric/ebgp_vxlan_fabric/evpn/.gitkeep
  roles/dtc/common/templates/ndfc_fabric/ebgp_vxlan_fabric/evpn/ebgp_vxlan_fabric_evpn.j2
  roles/dtc/common/templates/ndfc_fabric/ebgp_vxlan_fabric/flow_monitor/.gitkeep
  roles/dtc/common/templates/ndfc_fabric/ebgp_vxlan_fabric/flow_monitor/ebgp_vxlan_fabric_flow_monitor.j2
  roles/dtc/common/templates/ndfc_fabric/ebgp_vxlan_fabric/general/.gitkeep
  roles/dtc/common/templates/ndfc_fabric/ebgp_vxlan_fabric/general/ebgp_vxlan_fabric_general.j2
  roles/dtc/common/templates/ndfc_fabric/ebgp_vxlan_fabric/manageability/.gitkeep
  roles/dtc/common/templates/ndfc_fabric/ebgp_vxlan_fabric/manageability/ebgp_vxlan_fabric_manageability.j2
  roles/dtc/common/templates/ndfc_fabric/ebgp_vxlan_fabric/protocols/.gitkeep
  roles/dtc/common/templates/ndfc_fabric/ebgp_vxlan_fabric/protocols/ebgp_vxlan_fabric_protocols.j2
  roles/dtc/common/templates/ndfc_fabric/ebgp_vxlan_fabric/security/.gitkeep
  roles/dtc/common/templates/ndfc_fabric/ebgp_vxlan_fabric/security/ebgp_vxlan_fabric_security.j2
  roles/dtc/common/templates/ndfc_fabric/ebgp_vxlan_fabric/vpc/.gitkeep
  roles/dtc/common/templates/ndfc_fabric/ebgp_vxlan_fabric/vpc/ebgp_vxlan_fabric_vpc.j2
  roles/dtc/create/tasks/ebgp_vxlan/fabric.yml
  roles/dtc/create/tasks/main.yml
  roles/dtc/create/tasks/sub_main_ebgp_vxlan.yml
  roles/validate/files/defaults.yml
  roles/validate/files/rules/common_vxlan/.gitkeep
  roles/validate/files/rules/ebgp_vxlan/.gitkeep
  roles/validate/files/rules/ibgp_vxlan/.gitkeep
  roles/validate/files/rules/ibgp_vxlan/201_global_spanning_tree.py
  roles/validate/files/rules/ibgp_vxlan/202_global_underlay_mcast_trm.py
  roles/validate/files/rules/ibgp_vxlan/203_global_underlay_isis.py
  roles/validate/files/rules/ibgp_vxlan/204_global_bootstrap.py
  roles/validate/files/rules/ibgp_vxlan/205_underlay_ipv6.py
  roles/validate/files/rules/ibgp_vxlan/206_global_vnis_vlans.py
  roles/validate/files/rules/ibgp_vxlan/207_global_replication.py
  roles/validate/files/rules/ibgp_vxlan/208_manual_ipaddress_allocation.py
  roles/validate/files/rules/ibgp_vxlan/301_topology_switch_serial.py
  roles/validate/files/rules/ibgp_vxlan/302_topology_switch_management.py
  roles/validate/files/rules/ibgp_vxlan/303_topology_switch_role.py
  roles/validate/files/rules/ibgp_vxlan/304_topology_switch_interfaces_members_unique.py
  roles/validate/files/rules/ibgp_vxlan/305_topology_switch_interfaces_vpc.py
  roles/validate/files/rules/ibgp_vxlan/306_topology_switch_vpc_peers.py
  roles/validate/files/rules/ibgp_vxlan/307_topology_switch_preprovision.py
  roles/validate/files/rules/ibgp_vxlan/308_topology_switch_duplex.py
  roles/validate/files/rules/ibgp_vxlan/309_topology_switch_vpc_orphan.py
  roles/validate/files/rules/ibgp_vxlan/310_topology_switch_interface_breakouts.py
  roles/validate/files/rules/ibgp_vxlan/401_overlay_cross_reference.py
  roles/validate/files/rules/ibgp_vxlan/402_overlay_vrfs.py
  roles/validate/files/rules/ibgp_vxlan/403_overlay_networks.py
  roles/validate/files/rules/ibgp_vxlan/501_policy_cross_reference.py
  roles/validate/files/rules/ibgp_vxlan/502_policy_vrf_lite_cross_reference.py
  roles/validate/files/rules/ibgp_vxlan/503_route_control_check_ipaddress.py
  roles/validate/files/rules/ibgp_vxlan/505_policy_route_control_route_map.py
Labels: ready for review

#483 fix routing_tag for msd network
  roles/dtc/common/templates/ndfc_networks/msd_fabric/msd_fabric_networks.j2
Labels: ready for review

#482 Added support for VRF freeform: issue 442
  roles/dtc/common/templates/ndfc_vrfs/ndfc_attach_vrfs_loopbacks.j2
Labels: ready for review

#498 Update msd_fabric_general.j2
  roles/dtc/common/templates/ndfc_fabric/msd_fabric/general/msd_fabric_general.j2
  roles/dtc/common/templates/ndfc_fabric/msd_fabric/resources/msd_fabric_resources.j2
Labels: bug, ready for merge

#495 Added Support in External for pre-prov
  roles/dtc/common/templates/ndfc_inventory/dc_external_fabric/dc_external_fabric_inventory.j2
Labels: ready for review

#500 adding missing fabric attributes
  plugins/action/dtc/update_switch_hostname_policy.py
  roles/dtc/common/tasks/sub_main_ebgp_vxlan.yml
  roles/dtc/common/templates/ndfc_fabric/ebgp_vxlan_fabric/ebgp_vxlan_fabric_base.j2
  roles/dtc/common/templates/ndfc_fabric/ebgp_vxlan_fabric/evpn/ebgp_vxlan_fabric_evpn.j2
  roles/dtc/common/templates/ndfc_inventory.j2
  roles/dtc/create/tasks/sub_main_ebgp_vxlan.yml
  roles/dtc/deploy/tasks/main.yml
  roles/dtc/remove/tasks/common/switches.yml
  roles/dtc/remove/tasks/main.yml
  roles/dtc/remove/tasks/sub_main_ebgp_vxlan.yml
  roles/validate/files/defaults.yml
Labels: ready_for_revew_ebgp

#508 Update EFT branch with develop
  plugins/action/common/nac_dc_validate.py
  requirements.txt
  roles/dtc/common/templates/ndfc_inventory/dc_external_fabric/dc_external_fabric_inventory.j2
Labels: eft

#506 Adding possibility to configure policies under ebgp fabric
  roles/dtc/common/tasks/sub_main_ebgp_vxlan.yml
  roles/dtc/create/tasks/common/devices_discovery.yml
  roles/dtc/create/tasks/common/fabric.yml
  roles/dtc/create/tasks/common/policies.yml
  roles/dtc/create/tasks/main.yml
  roles/dtc/create/tasks/sub_main_ebgp_vxlan.yml
  roles/dtc/deploy/tasks/main.yml
  roles/dtc/remove/tasks/common/policy.yml
  roles/dtc/remove/tasks/main.yml
  roles/dtc/remove/tasks/sub_main_ebgp_vxlan.yml
  roles/validate/files/rules/ebgp_vxlan/501_policy_cross_reference.py
Labels: ready_for_revew_ebgp

#507 VPC for eBPG fabirc
  roles/dtc/common/tasks/sub_main_ebgp_vxlan.yml
  roles/dtc/create/tasks/common/devices_discovery.yml
  roles/dtc/create/tasks/common/vpc_peering.yml
  roles/dtc/create/tasks/main.yml
  roles/dtc/deploy/tasks/main.yml
  roles/dtc/remove/tasks/common/vpc_peers.yml
  roles/dtc/remove/tasks/main.yml
  roles/dtc/remove/tasks/sub_main_ebgp_vxlan.yml
Labels: ready_for_revew_ebgp
