Repository netascode/ansible-dc-vxlan, pull requests merged in 2025-08, with the labels that each got.

#520 Update vpc_peering.yml
  roles/dtc/create/tasks/common/vpc_peering.yml
Labels: bug

#512 add tcam allocation flag for VxLAN EVPN
  roles/dtc/common/templates/ndfc_fabric/dc_vxlan_fabric/advanced/dc_vxlan_fabric_advanced.j2
  roles/validate/files/defaults.yml
Labels: ready for review

#531 Issue 425
  roles/dtc/common/templates/ndfc_fabric/dc_vxlan_fabric/replication/dc_vxlan_fabric_replication.j2
  roles/dtc/common/templates/ndfc_fabric/ebgp_vxlan_fabric/evpn/ebgp_vxlan_fabric_evpn.j2
Labels: ready for review

#539 upate verson_compare import and fix issue 537
  plugins/action/dtc/manage_child_fabric_networks.py
  plugins/action/dtc/manage_child_fabric_vrfs.py
  roles/validate/files/rules/multisite/204_overlay_networks.py
Labels: ready for review

#541 update imports
  plugins/action/common/nac_dc_validate.py
  plugins/action/common/prepare_plugins/prep_001_fabric.py
  plugins/action/common/prepare_plugins/prep_002_list_defaults.py
  plugins/action/common/prepare_plugins/prep_103_topology_switches.py
  plugins/action/common/prepare_plugins/prep_104_fabric_overlay.py
  plugins/action/common/prepare_plugins/prep_105_topology_interfaces.py
  plugins/action/common/prepare_plugins/prep_107_vrf_lites.py
  plugins/action/common/prepare_plugins/prep_108_route_control.py
  plugins/action/common/prepare_plugins/prep_118_topology_edge_connections.py
  plugins/action/common/prepare_plugins/prep_999_verify.py
  plugins/action/dtc/prepare_msite_data.py
  plugins/action/dtc/unmanaged_edge_connections.py
  plugins/action/dtc/unmanaged_policy.py
  plugins/action/dtc/update_switch_hostname_policy.py
Labels: ready for review

#546 fix condition on ndfc_underlay_ip_address.j2
  roles/dtc/common/templates/ndfc_underlay_ip_address.j2
Labels: ready for review, 0.5.0

#549 Overlay networks support for eBGP fabric type
  roles/dtc/common/tasks/sub_main_ebgp_vxlan.yml
  roles/dtc/common/templates/ndfc_attach_networks.j2
  roles/dtc/create/tasks/main.yml
  roles/dtc/create/tasks/sub_main_ebgp_vxlan.yml
  roles/dtc/deploy/tasks/main.yml
  roles/dtc/remove/tasks/common_vxlan/networks.yml
  roles/dtc/remove/tasks/main.yml
  roles/dtc/remove/tasks/sub_main_ebgp_vxlan.yml
  roles/dtc/remove/tasks/sub_main_vxlan.yml
  roles/dtc/remove/tasks/vxlan/networks.yml
  roles/validate/files/rules/common_vxlan/403_overlay_networks.py
Labels: ready_for_revew_ebgp

#567 fix for fabric_loopback deployments
  roles/dtc/common/tasks/common/ndfc_interface_loopback.yml
  roles/dtc/common/tasks/external/ndfc_interface_loopback.yml
  roles/dtc/create/tasks/common/interfaces.yml
  roles/dtc/create/tasks/external/interfaces.yml
Labels: ready for review, 0.5.0

#561 Adding missing rules to external fabric and fixing nac_dc_validate to…
  plugins/action/common/nac_dc_validate.py
  roles/validate/files/rules/external/204_global_bootstrap.py
  roles/validate/files/rules/external/301_topology_switch_serial.py
  roles/validate/files/rules/external/302_topology_switch_management.py
  roles/validate/files/rules/external/303_topology_switch_role.py
  roles/validate/files/rules/external/304_topology_switch_interfaces_members_unique.py
  roles/validate/files/rules/external/305_topology_switch_interfaces_vpc.py
  roles/validate/files/rules/external/306_topology_switch_vpc_peers.py
  roles/validate/files/rules/external/307_topology_switch_preprovision.py
  roles/validate/files/rules/external/308_topology_switch_duplex.py
  roles/validate/files/rules/external/309_topology_switch_vpc_orphan.py
  roles/validate/files/rules/external/310_topology_switch_interface_breakouts.py
  roles/validate/files/rules/external/501_policy_cross_reference.py
  roles/validate/files/rules/external/502_policy_vrf_lite_cross_reference.py
  roles/validate/files/rules/external/503_route_control_check_ipaddress.py
  roles/validate/files/rules/external/505_policy_route_control_route_map.py
  roles/validate/files/rules/isn/204_global_bootstrap.py
Labels: ready for review, 0.5.0

#563 Add support for ipv6 route map under vrf
  roles/dtc/common/templates/ndfc_vrfs/dc_vxlan_fabric/dc_vxlan_fabric_vrfs.j2
  roles/dtc/common/templates/ndfc_vrfs/msd_fabric/child_fabric/3.2/msd_child_fabric_vrf.j2
  roles/dtc/common/templates/ndfc_vrfs/msd_fabric/child_fabric/msd_child_fabric_vrf.j2
  roles/dtc/common/templates/ndfc_vrfs/msd_fabric/msd_fabric_vrfs.j2
  roles/validate/files/defaults.yml
Labels: 0.5.0
