Repository netascode/ansible-dc-vxlan, pull requests merged in 2025-04, with the labels that each got.

#330 Fix rule 305 - Not able to create same vpc_id with different vPC pair
  roles/validate/files/rules/vxlan/305_topology_switch_interfaces_vpc.py
Labels: ready for review

#326 Refactor msite vrf and network child fabric mgmt plugins
  plugins/action/dtc/fabrics_config_save.py
  plugins/action/dtc/fabrics_deploy.py
  plugins/action/dtc/manage_child_fabric_networks.py
  plugins/action/dtc/manage_child_fabric_vrfs.py
  plugins/action/dtc/prepare_msite_data.py
  roles/dtc/remove/tasks/msd/networks.yml
  roles/dtc/remove/tasks/msd/vrfs.yml
  roles/validate/files/rules/multisite/201_overlay_cross_reference.py
  roles/validate/files/rules/multisite/202_overlay_child_fabric_cross_reference.py
  roles/validate/files/rules/multisite/203_overlay_vrfs.py
  roles/validate/files/rules/multisite/204_overlay_networks.py
Labels: ready for review, 0.4.1

#339 Updated jinja template to support defaults in links
  roles/dtc/common/templates/ndfc_fabric_links.j2
  roles/validate/files/defaults.yml
Labels: 0.4.1

#341 Fix for testing issue 340
  plugins/action/common/prepare_plugins/prep_103_topology_switches.py
  roles/dtc/common/templates/ndfc_fabric_links.j2
Labels: ready for review, 0.4.1

#342 quick fix for prep118
  plugins/action/common/prepare_plugins/prep_118_topology_edge_connections.py
  roles/dtc/common/tasks/sub_main_isn.yml
  roles/dtc/common/templates/ndfc_edge_connections.j2
  roles/dtc/remove/tasks/sub_main_isn.yml
Labels: ready for review, 0.4.1

#347 Update to handle another policy freeform example
  roles/dtc/common/templates/ndfc_policy.j2
Labels: ready for review, 0.4.1

#351 Remove space from ip and asn lists
  roles/dtc/common/templates/ndfc_fabric/msd_fabric/dci/msd_fabric_dci.j2
Labels: bug, ready for review, 0.4.1

#344 fix policy jinja to add new line for BANNER
  roles/dtc/common/templates/ndfc_policy.j2
Labels: ready for review, 0.4.1

#362 Release 0.4.1
  docs/maintainers.md
Labels: 0.4.1

#368 Comment out unused task (to avoid undefined variable error)
  roles/dtc/remove/tasks/sub_main_external.yml
Labels: ready for review

#353 fix BFD authentication
  roles/dtc/common/templates/ndfc_fabric/dc_vxlan_fabric/protocols/dc_vxlan_fabric_protocols.j2
Labels: ready for review, 0.4.2

#367 Fixed layer2_host_interfacde_mtu typo
  roles/dtc/common/templates/ndfc_fabric/dc_vxlan_fabric/advanced/dc_vxlan_fabric_advanced.j2
  roles/validate/files/defaults.yml
  tests/integration/host_vars/examples/fabric_empty_example/underlay.yaml
  tests/integration/host_vars/examples/fabric_full_large_example/underlay.yaml
  tests/integration/host_vars/examples/fabric_full_small_isis_ingress_example/underlay.yaml
  tests/integration/host_vars/examples/fabric_full_small_isis_multicast_asm_example/underlay.yaml
  tests/integration/host_vars/examples/fabric_full_small_isis_multicast_bidir_example/underlay.yaml
  tests/integration/host_vars/examples/fabric_full_small_ospf_ingress_example/underlay.yaml
  tests/integration/host_vars/examples/fabric_full_small_ospf_multicast_asm_example/underlay.yaml
  tests/integration/host_vars/examples/fabric_full_small_ospf_multicast_bidir_example/underlay.yaml
Labels: ready for review
