Repository netascode/ansible-dc-vxlan, pull requests merged in 2025-03, with the labels that each got.

#297 Expose mcast address back to child fabric in msd
  plugins/action/dtc/manage_child_fabric_networks.py
  roles/dtc/common/templates/ndfc_networks/msd_fabric/child_fabric/msd_child_fabric_network.j2
Labels: ready for review

#304 Update isn_fabric_advanced.j2 add all NXAPI parameters and update defaults
  roles/dtc/common/templates/ndfc_fabric/isn_fabric/advanced/isn_fabric_advanced.j2
  roles/validate/files/defaults.yml
Labels: ready for review

#312 Fix for vpc interfaces being created on non-leaf roles
  plugins/action/common/prepare_plugins/prep_106_topology_vpc_interfaces.py
  roles/dtc/common/templates/ndfc_interfaces/ndfc_interface_vpc.j2
Labels: ready for review

#309 Fix and refactor to convert range macro
  plugins/plugin_utils/data_model_keys.py
  roles/dtc/common/templates/macros/convert_ranges.j2
  roles/dtc/common/templates/ndfc_fabric/dc_vxlan_fabric/advanced/dc_vxlan_fabric_advanced.j2
  roles/dtc/common/templates/ndfc_fabric/dc_vxlan_fabric/dc_vxlan_fabric_base.j2
  roles/dtc/common/templates/ndfc_interfaces/ndfc_interface_trunk.j2
  roles/dtc/common/templates/ndfc_interfaces/ndfc_interface_trunk_po.j2
  roles/dtc/common/templates/ndfc_interfaces/ndfc_interface_vpc.j2
  roles/validate/files/defaults.yml
Labels: ready for review

#313 Update github templates to add quick copy option
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/documentation_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: ready for review

#300 Fix for VRF/Network Remove in MSD When Running End-to-End Workflow
  plugins/action/dtc/manage_child_fabric_networks.py
  plugins/action/dtc/manage_child_fabric_vrfs.py
  plugins/action/dtc/unmanaged_child_fabric_networks.py
  plugins/action/dtc/unmanaged_child_fabric_vrfs.py
  roles/dtc/common/tasks/main.yml
  roles/dtc/common/templates/ndfc_vrfs/msd_fabric/child_fabric/msd_child_fabric_vrf.j2
  roles/dtc/create/tasks/msd/vrfs_networks.yml
  roles/dtc/remove/tasks/msd/networks.yml
  roles/dtc/remove/tasks/msd/vrfs.yml
  tests/sanity/ignore-2.14.txt
  tests/sanity/ignore-2.15.txt
  tests/sanity/ignore-2.16.txt
  tests/sanity/ignore-2.17.txt
Labels: ready for review, r0.4.1

#310 Update to check for parent MSD fabric
  roles/dtc/create/tasks/vxlan/vrfs_networks.yml
  roles/dtc/remove/tasks/vxlan/networks.yml
  roles/dtc/remove/tasks/vxlan/vrfs.yml
Labels: ready for review, r0.4.1

#321 Add bootstrap defaults
  roles/validate/files/defaults.yml
Labels: ready for review, 0.4.1

#299 Updates to fix bootstrap without local DHCP
  plugins/action/common/nac_dc_validate.py
  plugins/plugin_utils/data_model_keys.py
  roles/dtc/common/templates/ndfc_fabric/dc_external_fabric/bootstrap/dc_external_fabric_bootstrap.j2
  roles/dtc/common/templates/ndfc_fabric/dc_vxlan_fabric/bootstrap/dc_vxlan_fabric_bootstrap.j2
  roles/dtc/common/templates/ndfc_fabric/isn_fabric/bootstrap/isn_fabric_bootstrap.j2
  roles/validate/files/rules/external/.gitkeep
  roles/validate/files/rules/external/204_global_bootstrap.py
  roles/validate/files/rules/isn/204_global_bootstrap.py
  roles/validate/files/rules/vxlan/204_global_bootstrap.py
Labels: ready for review, 0.4.1

#319 Extra fabric settings v2
  plugins/action/dtc/existing_links_check.py
  roles/dtc/common/templates/ndfc_fabric/dc_external_fabric/advanced/dc_external_fabric_advanced.j2
  roles/dtc/common/templates/ndfc_fabric/dc_vxlan_fabric/advanced/dc_vxlan_fabric_advanced.j2
  roles/dtc/common/templates/ndfc_fabric/dc_vxlan_fabric/protocols/dc_vxlan_fabric_protocols.j2
  roles/dtc/common/templates/ndfc_fabric/dc_vxlan_fabric/vpc/dc_vxlan_fabric_vpc.j2
  roles/dtc/common/templates/ndfc_fabric/isn_fabric/advanced/isn_fabric_advanced.j2
  roles/dtc/common/templates/ndfc_interfaces/ndfc_interface_access.j2
  roles/dtc/common/templates/ndfc_interfaces/ndfc_interface_access_po.j2
  roles/dtc/common/templates/ndfc_interfaces/ndfc_interface_po_routed.j2
  roles/dtc/common/templates/ndfc_interfaces/ndfc_interface_routed.j2
  roles/dtc/common/templates/ndfc_interfaces/ndfc_interface_trunk.j2
  roles/dtc/common/templates/ndfc_interfaces/ndfc_interface_trunk_po.j2
  roles/dtc/common/templates/ndfc_interfaces/ndfc_interface_vpc.j2
  roles/dtc/common/templates/ndfc_interfaces/ndfc_loopback_interfaces.j2
  roles/dtc/common/templates/ndfc_interfaces/ndfc_sub_interface_routed.j2
  roles/dtc/common/templates/ndfc_inventory.j2
  roles/dtc/common/templates/ndfc_policy.j2
  roles/dtc/create/tasks/common/interfaces.yml
  roles/dtc/create/tasks/common/links.yml
  roles/dtc/create/tasks/external/interfaces.yml
  roles/validate/files/defaults.yml
Labels: ready for review, 0.4.1

#328 Fixes for Rules & Templates
  roles/dtc/common/templates/ndfc_fabric/dc_vxlan_fabric/vpc/dc_vxlan_fabric_vpc.j2
  roles/validate/files/rules/external/204_global_bootstrap.py
  roles/validate/files/rules/isn/204_global_bootstrap.py
  roles/validate/files/rules/vxlan/204_global_bootstrap.py
Labels: ready for review, 0.4.1
