Repository netascode/ansible-dc-vxlan, pull requests merged in 2025-05, with the labels that each got.

#372 PTP fix 371
  roles/dtc/common/templates/ndfc_fabric/dc_external_fabric/advanced/dc_external_fabric_advanced.j2
Labels: ready for review, 0.4.2

#370 Rework Issues 239 & 262
  roles/dtc/common/tasks/msd/ndfc_child_fabrics.yml
  roles/dtc/common/templates/ndfc_fabric/dc_vxlan_fabric/advanced/dc_vxlan_fabric_advanced.j2
  roles/dtc/common/templates/ndfc_fabric/dc_vxlan_fabric/flow_monitor/dc_vxlan_fabric_flow_monitor.j2
  roles/dtc/common/templates/ndfc_fabric/dc_vxlan_fabric/general/dc_vxlan_fabric_general.j2
  roles/dtc/common/templates/ndfc_fabric/dc_vxlan_fabric/protocols/dc_vxlan_fabric_protocols.j2
  roles/dtc/common/templates/ndfc_fabric/dc_vxlan_fabric/replication/dc_vxlan_fabric_replication.j2
  roles/dtc/common/templates/ndfc_fabric/dc_vxlan_fabric/resources/dc_vxlan_fabric_resources.j2
  roles/dtc/common/templates/ndfc_fabric/dc_vxlan_fabric/security/dc_vxlan_fabric_security.j2
  roles/dtc/common/templates/ndfc_fabric/dc_vxlan_fabric/vpc/dc_vxlan_fabric_vpc.j2
  roles/dtc/common/templates/ndfc_networks/dc_vxlan_fabric/dc_vxlan_fabric_networks.j2
  roles/dtc/common/templates/ndfc_vrfs/dc_vxlan_fabric/dc_vxlan_fabric_vrfs.j2
  roles/dtc/common/templates/ndfc_vrfs/ndfc_attach_vrfs_loopbacks.j2
  roles/dtc/create/tasks/vxlan/vrfs_networks.yml
  roles/validate/files/defaults.yml
  roles/validate/files/rules/vxlan/205_underlay_ipv6.py
Labels: ready for review, 0.4.2

#376 Remove fabric_links reference for External Fabrics. Fix for External Fabric Inventory templates
  roles/dtc/common/tasks/sub_main_external.yml
  roles/dtc/common/templates/ndfc_fabric/dc_external_fabric/advanced/dc_external_fabric_advanced.j2
  roles/dtc/common/templates/ndfc_fabric/dc_external_fabric/general/dc_external_fabric_general.j2
  roles/dtc/common/templates/ndfc_inventory.j2
  roles/dtc/common/templates/ndfc_inventory/dc_external_fabric/dc_external_fabric_inventory.j2
  roles/dtc/remove/tasks/sub_main_external.yml
Labels: bug, ready for review, 0.4.2

#369 Update existing_links_check.py
  plugins/action/dtc/existing_links_check.py
  plugins/action/dtc/links_filter_and_remove.py
Labels: bug, ready for review, 0.4.2

#382 Update Missing Tags
  roles/dtc/create/tasks/sub_main_msd.yml
  roles/dtc/remove/tasks/sub_main_msd.yml
Labels: 0.4.2

#381 Ignore poap.bootstrap flag for device that is already discovered
  plugins/action/dtc/get_poap_data.py
Labels: ready for review, 0.4.2

#384 Fixes for isn and more for external
  roles/dtc/common/tasks/sub_main_external.yml
  roles/dtc/common/tasks/sub_main_isn.yml
  roles/dtc/common/templates/ndfc_fabric/dc_external_fabric/advanced/dc_external_fabric_advanced.j2
  roles/dtc/common/templates/ndfc_fabric/dc_external_fabric/flow_monitor/dc_external_fabric_flow_monitor.j2
  roles/dtc/common/templates/ndfc_fabric/dc_external_fabric/general/dc_external_fabric_general.j2
  roles/dtc/common/templates/ndfc_fabric/dc_external_fabric/resources/dc_external_fabric_resources.j2
  roles/dtc/common/templates/ndfc_fabric/isn_fabric/advanced/isn_fabric_advanced.j2
  roles/dtc/common/templates/ndfc_fabric/isn_fabric/general/isn_fabric_general.j2
  roles/dtc/common/templates/ndfc_inventory/isn_fabric/isn_fabric_inventory.j2
  roles/dtc/create/tasks/sub_main_isn.yml
  roles/dtc/remove/tasks/isn/.gitkeep
  roles/dtc/remove/tasks/isn/links.yml
  roles/dtc/remove/tasks/main.yml
  roles/dtc/remove/tasks/sub_main_isn.yml
Labels: 0.4.2

#361 L2 and l3 vni ranges in fabric settings
  roles/dtc/common/templates/ndfc_fabric/dc_vxlan_fabric/resources/dc_vxlan_fabric_resources.j2
  roles/dtc/common/templates/ndfc_fabric/msd_fabric/general/msd_fabric_general.j2
  roles/validate/files/defaults.yml
  roles/validate/files/rules/multisite/205_vnis.py
  roles/validate/files/rules/vxlan/206_global_vnis_vlans.py
Labels: ready for review, 0.4.2

#387 Add subnet on default_gateway for preprovision
  roles/dtc/common/templates/ndfc_inventory/common/fabric_inventory.j2
  roles/dtc/common/templates/ndfc_inventory/dc_external_fabric/dc_external_fabric_inventory.j2
  roles/dtc/common/templates/ndfc_inventory/dc_vxlan_fabric/dc_vxlan_fabric_inventory.j2
  roles/validate/files/rules/vxlan/307_topology_switch_preprovision.py
Labels: 0.4.2

#392 Fix BGP Graceful Restart for VRF-Lite
  roles/dtc/common/templates/ndfc_vrf_lite/ndfc_vrf_lite_ebgp.j2
Labels: ready for review, 0.4.2

#396 Update external fabric idempotency
  roles/dtc/create/tasks/external/fabric.yml
Labels: 0.4.2
