Repository netascode/ansible-dc-vxlan, pull requests merged in 2025-09, with the labels that each got.

#576 Update existing_links_check.py for intra unnumbered
  plugins/action/dtc/existing_links_check.py
Labels: ready for review

#538 Support of individual per-switch credentials
  SWITCH_CREDENTIALS_GUIDE.md
  plugins/action/common/get_credentials.py
  roles/dtc/common/tasks/common/ndfc_inventory.yml
  roles/dtc/common/tasks/common/ndfc_inventory_no_bootstrap.yml
  roles/dtc/common/tasks/external/ndfc_inventory.yml
Labels: ready for review, 0.5.0

#584 fix edge connections to support multiple links between switches
  roles/dtc/common/templates/ndfc_edge_connections.j2
Labels: ready for review

#606 Update 200_global_bgp_asn.py
  roles/validate/files/rules/common/200_global_bgp_asn.py
Labels: 0.5.0
